apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: default
  labels:
    app: microservicio-employee-service
    role: backend
    stage: production
    version: v1.0.0
spec:
  replicas: {{ .values.appReplicaCount }}
  selector:
    matchLabels:
      app: microservicio-employee-service
      version: v1.0.0  
  template:
    metadata:
      labels:
        app: microservicio-employee-service
        version: v1.0.0
    spec:
      containers:                  
        - name: microservicio-employee-service
          image: maktup/employee-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .values.containerPort }}
          #IMPORTANTE: Si NO se configura [CPU/RAM] NO funcionara el: 'AUTOSCALING'.     
          resources:
            limits:
              cpu: {{ .values.resourcesCpu }}
          env:
          #CONFIGURACION DE 'SECRETs': 
          - name: DUMMY_VARIABLE
            value: javaman
            
          - name: BOOTADMIN_USUARIO
            valueFrom:
              secretKeyRef:
                key: BOOTADMIN_PASSWORD
                name: employee-service-secret
            
          - name: BOOTADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: BOOTADMIN_PASSWORD
                name: employee-service-secret
