apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-deploy
    role: backend
    stage: production
    version: v1.0.0
  name: my-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-deploy
  type: NodePort
