apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-deploy
    role: backend
    stage: production
    version: v1.0.0
  name: my-service
spec:
  ports:
  - port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.servicePort }}
  selector:
    app: my-deploy
  type: NodePort
