apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deploy
    role: backend
    stage: production
    version: v1.0.0
  name: my-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-deploy
      role: backend
      stage: production
      version: v1.0.0
  template:
    metadata:
      labels:
        app: my-deploy
        role: backend
        stage: production
        version: v1.0.0
    spec:
      containers:
      - image: maktup/employee-service:latest
        name: employee-service
