apiVersion: v1
kind: Secret
metadata:
  name: my-service-secret
  namespace: default
  labels:
    app: my-deploy
    role: backend
    stage: production
    version: v1.0.0
  #-------------------------------------------------------------------#
  #---------------------- CONFIGURACION SECRETs ----------------------#
  #--------- Formato BASE64 (https://www.base64encode.net/) ----------#
  #-------------------------------------------------------------------#
data:
  BOOTADMIN_USUARIO: YWRtaW4=
  BOOTADMIN_PASSWORD: YWRtaW4=
